#!/usr/bin/env python3
"""DRY analysis for OpenRiver using only the Python standard library.

Reports duplicate normalized line blocks, repeated string literals, and repeated
function shapes. The script is intentionally advisory: it exits non-zero only
when duplicate code blocks exceed --max-blocks so it can be used as a quality
budget without blocking on benign repeated test vocabulary.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import io
import tokenize
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PATHS = [ROOT / "openriver", ROOT / "tests", ROOT / "scripts"]


@dataclass(frozen=True)
class BlockHit:
    path: str
    line: int
    text: str


def python_files(paths: list[Path]) -> list[Path]:
    files: list[Path] = []
    for path in paths:
        if path.is_file() and path.suffix == ".py":
            files.append(path)
        elif path.is_dir():
            files.extend(p for p in path.rglob("*.py") if "__pycache__" not in p.parts)
    return sorted(set(files))


def normalize_line(line: str) -> str:
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return ""
    return " ".join(stripped.split())


def duplicate_blocks(files: list[Path], block_size: int) -> dict[str, list[BlockHit]]:
    blocks: dict[str, list[BlockHit]] = defaultdict(list)
    for path in files:
        raw_lines = path.read_text(errors="ignore").splitlines()
        normalized = [(i + 1, normalize_line(line)) for i, line in enumerate(raw_lines)]
        normalized = [(line, text) for line, text in normalized if text]
        for idx in range(0, max(0, len(normalized) - block_size + 1)):
            chunk = normalized[idx : idx + block_size]
            text = "\n".join(part for _, part in chunk)
            digest = hashlib.sha256(text.encode()).hexdigest()
            blocks[digest].append(BlockHit(path.relative_to(ROOT).as_posix(), chunk[0][0], text))
    return {digest: hits for digest, hits in blocks.items() if len({(h.path, h.line) for h in hits}) > 1}


def string_literals(files: list[Path]) -> Counter[str]:
    counts: Counter[str] = Counter()
    for path in files:
        try:
            tokens = tokenize.generate_tokens(io.StringIO(path.read_text()).readline)
            for tok in tokens:
                if tok.type == tokenize.STRING:
                    try:
                        value = ast.literal_eval(tok.string)
                    except Exception:
                        continue
                    if isinstance(value, str) and len(value) >= 8 and "\n" not in value:
                        counts[value] += 1
        except tokenize.TokenError:
            continue
    return counts


class Shape(ast.NodeTransformer):
    def visit_Name(self, node: ast.Name) -> ast.AST:  # noqa: N802
        return ast.copy_location(ast.Name(id="NAME", ctx=node.ctx), node)

    def visit_arg(self, node: ast.arg) -> ast.AST:  # noqa: N802
        return ast.copy_location(ast.arg(arg="ARG", annotation=None), node)

    def visit_Constant(self, node: ast.Constant) -> ast.AST:  # noqa: N802
        if isinstance(node.value, str):
            return ast.copy_location(ast.Constant(value="STR"), node)
        if isinstance(node.value, (int, float, bool)) or node.value is None:
            return ast.copy_location(ast.Constant(value="CONST"), node)
        return node


def function_shapes(files: list[Path]) -> dict[str, list[str]]:
    shapes: dict[str, list[str]] = defaultdict(list)
    for path in files:
        try:
            tree = ast.parse(path.read_text(), filename=str(path))
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                body_len = len(getattr(node, "body", []))
                if body_len < 3:
                    continue
                clone = Shape().visit(ast.fix_missing_locations(node))
                dumped = ast.dump(clone, include_attributes=False)
                digest = hashlib.sha256(dumped.encode()).hexdigest()
                shapes[digest].append(f"{path.relative_to(ROOT).as_posix()}:{node.lineno}:{node.name}")
    return {digest: hits for digest, hits in shapes.items() if len(hits) > 1}


def render_report(files: list[Path], block_size: int, max_blocks: int) -> tuple[str, int]:
    blocks = duplicate_blocks(files, block_size)
    literals = string_literals(files)
    shapes = function_shapes(files)
    repeated_literals = [(s, c) for s, c in literals.most_common() if c >= 4]

    out: list[str] = []
    out.append("# OpenRiver DRY Analysis")
    out.append("")
    out.append("Generated by `python scripts/dry_analysis.py --format markdown`.")
    out.append("")
    out.append("## Summary")
    out.append("")
    out.append(f"- Python files scanned: {len(files)}")
    out.append(f"- Duplicate normalized {block_size}-line blocks: {len(blocks)}")
    out.append(f"- Repeated string literals appearing 4+ times: {len(repeated_literals)}")
    out.append(f"- Repeated function shapes: {len(shapes)}")
    out.append(f"- Duplicate block budget: <= {max_blocks}")
    out.append("")
    out.append("## Duplicate code blocks")
    out.append("")
    if not blocks:
        out.append("No duplicate normalized code blocks found at the configured block size.")
    else:
        for n, (_, hits) in enumerate(sorted(blocks.items(), key=lambda item: (-len(item[1]), item[1][0].path))[:20], 1):
            out.append(f"### Block {n} — {len(hits)} occurrences")
            for hit in hits[:8]:
                out.append(f"- `{hit.path}:{hit.line}`")
            out.append("```text")
            out.append(hits[0].text)
            out.append("```")
            out.append("")
    out.append("## Repeated string literals")
    out.append("")
    if not repeated_literals:
        out.append("No heavily repeated string literals found.")
    else:
        for literal, count in repeated_literals[:30]:
            out.append(f"- `{literal}` — {count} occurrences")
    out.append("")
    out.append("## Repeated function shapes")
    out.append("")
    if not shapes:
        out.append("No repeated function shapes found.")
    else:
        for n, hits in enumerate(shapes.values(), 1):
            out.append(f"### Shape {n}")
            for hit in hits:
                out.append(f"- `{hit}`")
            out.append("")
    out.append("## Recommendation")
    out.append("")
    if len(blocks) <= max_blocks:
        out.append("DRY budget passes. Current duplication is low enough for this MVP; repeated test vocabulary is acceptable until fixtures grow further.")
        exit_code = 0
    else:
        out.append("DRY budget fails. Extract helpers/fixtures for the duplicate blocks above before growing the suite further.")
        exit_code = 2
    return "\n".join(out) + "\n", exit_code


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("paths", nargs="*", default=[str(p.relative_to(ROOT)) for p in DEFAULT_PATHS])
    parser.add_argument("--block-size", type=int, default=6)
    parser.add_argument("--max-blocks", type=int, default=2)
    parser.add_argument("--format", choices=["text", "markdown"], default="text")
    args = parser.parse_args()
    files = python_files([ROOT / p for p in args.paths])
    report, exit_code = render_report(files, args.block_size, args.max_blocks)
    if args.format == "text":
        report = report.replace("# OpenRiver DRY Analysis", "OpenRiver DRY Analysis")
    print(report, end="")
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
